### ISSUE TITLE
BAG2024_XAS_003

### ISSUE THREAD

**Issue by alex-belozerov** [MaterialsGalaxy/larch-tools#47]

**Comment by alex-belozerov** [comment]
1. The history is here:
https://muongalaxy.stfc.ac.uk/u/a.belozerov/h/bag2024xas003

2. I dropped the following files as they are not listed in the table:
643646_Rh2O3_SiO2_BR_1.dat
643689_Rh2O3_SiO2_AR_9.dat

3. I also dropped the one below, as there is 'no' in the column 'Give scan to user':
643653_Rh2O3_Cr2O3_SiO2_BR_1.dat

4. Following the Patrick's suggestion, I looked at all individual plots and noticed that in some cases the fit looks strange:

**643671_Rh_Al2O3_BR_1.dat**
![643671_Rh_Al2O3_BR_1](https://github.com/MaterialsGalaxy/larch-tools/assets/70074421/16daab85-50b0-44c3-ae6c-85d69ce646fd)

**643673_Rh_Al2O3_BR_3.dat**
![643673_Rh_Al2O3_BR_3](https://github.com/MaterialsGalaxy/larch-tools/assets/70074421/d465e036-ae49-4dae-a7b1-fb624ca1066e)

**643677_Rh_Al2O3_BR_7.dat**
![643677_Rh_Al2O3_BR_7](https://github.com/MaterialsGalaxy/larch-tools/assets/70074421/a72b6ac8-a458-4bde-b0d1-d1f9920ea7ce)

**643703_Rh2O3_DR_6.dat**
![643703_Rh2O3_DR_6](https://github.com/MaterialsGalaxy/larch-tools/assets/70074421/d6acf9e5-73a4-4702-b9bc-c3bb4f98c6ef)

5. All merged plots seem sensible. However, I couldn't plot the merged Athena projects together or even individually using Larch plot. The corresponding error message is below. @patrick-austin , could you please have a look?

Traceback (most recent call last):
File "/srv/galaxy/var/shed_tools/toolshed.g2.bx.psu.edu/repos/muon-spectroscopy-computational-project/larch_plot/002c18a3e642/larch_plot/larch_plot.py", line 87, in <module> main(dat_files.split(","), input_values["plots"])
File "/srv/galaxy/var/shed_tools/toolshed.g2.bx.psu.edu/repos/muon-spectroscopy-computational-project/larch_plot/002c18a3e642/larch_plot/larch_plot.py", line 37, in main label = params.annotation or params.file or params.id AttributeError: 'Group' object has no attribute 'file'

6. Please find below all merged plots as obtained by Larch Athena. 

![Rh2O3 DR (no SiO2)](https://github.com/MaterialsGalaxy/larch-tools/assets/70074421/8d35e8bf-acce-4774-ab91-cd83c7e1483e)
![Rh2O3 DR SiO2](https://github.com/MaterialsGalaxy/larch-tools/assets/70074421/86e92974-7d4f-4a65-bf53-b540084240c8)
![Rh2O3 post (AR)](https://github.com/MaterialsGalaxy/larch-tools/assets/70074421/7698b828-54fc-45f5-bea5-3d31ad3b375e)
![Rh2O3 pre (BR)](https://github.com/MaterialsGalaxy/larch-tools/assets/70074421/ca1d04b3-8bbd-4c86-a119-51deb2bdf2cf)
![Rh2O3_Al2O3](https://github.com/MaterialsGalaxy/larch-tools/assets/70074421/fa5e98d9-945c-4a3b-8376-f3f20219d376)
![Rh2O3_Cr2O3_SiO2_BR](https://github.com/MaterialsGalaxy/larch-tools/assets/70074421/cc9e60bf-ede3-47e4-b278-3291b03d56c2)
![Rh2O3_CrOx_SiO2 post (AR)](https://github.com/MaterialsGalaxy/larch-tools/assets/70074421/622de893-28b8-4510-b56c-31e026decb0b)
![Rh2O3_SiO2 post (AR)](https://github.com/MaterialsGalaxy/larch-tools/assets/70074421/b35140a4-8477-4e5d-b830-44a7461b2b49)
![Rh2O3_SiO2 pre](https://github.com/MaterialsGalaxy/larch-tools/assets/70074421/8e88beed-fa05-46f0-9cf6-d94024314c50)

**Comment by patrick-austin** [comment]
I've not had a chance to go through things in detail, but:

- Individual fits: I suspect when these are determining the edge energy, it's getting it wrong (i.e. identifying a random spike in the noise as the "edge" and determining the pre/post edge regions based on this. I think enabling `Pre-edge normalization` and then setting `Edge energy (eV)` to be the expected value (23219.9eV according to https://www.ruppweb.org/Xray/elements.html but might that's for the pure metal - could use the Iref in the data like we talked about this morning). When merged the noise is reduced so at the point it's probably able to identify the peak correctly.
- The error in Larch Plot may be fixed by the most recent vesion (0.9.74+galaxy1) which should now be on the website. If not, it's trying to use the `file` attribute only when the annotation field wasn't set during Athena. If the latest version doesn't fix then could work around by setting the annotation (but let me know anyway so can fix it if need be).

**Comment by alex-belozerov** [comment]
Patrick, thanks for your reply. 

> * Individual fits: I suspect when these are determining the edge energy, it's getting it wrong (i.e. identifying a random spike in the noise as the "edge" and determining the pre/post edge regions based on this. I think enabling `Pre-edge normalization` and then setting `Edge energy (eV)` to be the expected value (23219.9eV according to https://www.ruppweb.org/Xray/elements.html but might that's for the pure metal - could use the Iref in the data like we talked about this morning). When merged the noise is reduced so at the point it's probably able to identify the peak correctly.

The `Pre-edge normalization` with `Edge energy (eV)` set to 23219.9eV (https://www.ruppweb.org/Xray/elements.html) fixed the problem. 

> * The error in Larch Plot may be fixed by the most recent vesion (0.9.74+galaxy1) which should now be on the website. If not, it's trying to use the `file` attribute only when the annotation field wasn't set during Athena. If the latest version doesn't fix then could work around by setting the annotation (but let me know anyway so can fix it if need be).

The last version you mentioned works fine. The final plot is shown below:
![Galaxy453- 0_flat](https://github.com/MaterialsGalaxy/larch-tools/assets/70074421/ed8f1a12-1018-4088-aec2-b02cd7cc8a12)
